# Generated by Django 5.2.5 on 2025-08-10 16:15

import django.db.models.deletion
import releases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web/Desktop')], default='android', max_length=20)),
                ('version', models.CharField(help_text='SemVer, ej: 1.2.0', max_length=50)),
                ('build_number', models.CharField(blank=True, help_text='Opcional', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=releases.models.upload_path)),
                ('external_link', models.URLField(blank=True, help_text='Si no subes archivo (TestFlight, Play Console, etc.)')),
                ('release_notes', models.TextField(blank=True)),
                ('is_prerelease', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='releases.app')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('app', 'platform', 'version')},
            },
        ),
    ]
