# Generated by Django 5.2.5 on 2025-08-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='reference_image1',
            field=models.ImageField(blank=True, null=True, upload_to='reference/', verbose_name='Imagen de referencia 1'),
        ),
        migrations.AddField(
            model_name='app',
            name='reference_image2',
            field=models.ImageField(blank=True, null=True, upload_to='reference/', verbose_name='Imagen de referencia 2'),
        ),
        migrations.AddField(
            model_name='app',
            name='reference_image3',
            field=models.ImageField(blank=True, null=True, upload_to='reference/', verbose_name='Imagen de referencia 3'),
        ),
    ]
